### ISSUE TITLE
Suggestion: Can you add a warning system?

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/BanSystem-Nukkit#1]
Adding a warning would really make the plugin more useful. Can you add it, please? For example, if you use `/warn <player> <reason>`, <player> will kicked and a warning is logged. If <player> get over three warnings, <player> will be banned.

**Comment by Mundschutziii** [comment]
Hi, I can add such a system soon! Thanks for your suggestion. :-)

**Comment by snaildos** [comment]
Oh yes!!

**Comment by Mundschutziii** [comment]
In the next few hours an update will be released, in which the warning system is now available.

**Comment by good777LUCKY** [comment]
Cool!
