### ISSUE TITLE
Spamming server lgos

### ISSUE THREAD

**Issue by snaildos** [llama-development/BanSystem-Nukkit#3]
Please have a option to disable the MONGODB connection SPAM when the server is running.
Thank's!!

Oh ye and add tempban and warnings if you can.

**Comment by Mundschutziii** [comment]
Hi, I can't disable spam directly.
Warnings and Tempbans will be added in one of the next updates ^^

**Comment by snaildos** [comment]
AWSOME!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
